FROM node:12-alpine

WORKDIR /usr/app

COPY package*.json ./

RUN npm ci

ARG NODE_ENV
ARG PORT
ARG API_KEY

ENV NODE_ENV=$NODE_ENV \
    PORT=$PORT \
    API_KEY=$API_KEY

COPY . ./

EXPOSE $PORT

CMD ["npm", "run", "start:dev"]
